### PR TITLE
aq.objects({ preserveGroups }) Draft Proposal

### PR DESCRIPTION
**Pull request by lsh**
**Problem statement:** Arquero offers a grouping functionality, which is a powerful tool when working with data. However, when calling `aqTable.objects()` on a grouped table, the output is a flat array which does not preserve the groupings.

**Use cases:** There are many reasons for outputting a data structure that represents groups. One such reason is for quickly switching between subsets of data without recomputing the output. Usually this would involve using filter several times.

Another use case is when working with D3. Nested arrays can be incredibly useful for grouping data in a way such as:
```javascript
const data = [[{group: 'a', data: 1}, {group: 'a', data: 2}, {group: 'a', data: 3}],
	      [{group: 'b', data: 1}, {group: 'b', data: 2}, {group: 'b', data: 3}],
              [{group: 'c', data: 1}, {group: 'c', data: 2}, {group: 'c', data: 3}]];
              
svg.selectAll('g')
    .data(data)
    .join('g')
    	// transformation of groups
    .selectAll('rect')
    .data(d => d)
    .join('rect')
    	// rect attributes
```

**Prior art:** grouped output is implement in a few data munging libraries. One such example is [tidyjs](https://github.com/pbeshai/tidy), which is a main inspiration for this proposal. Tidy offers a `groupBy.{entries(), map(), object()}` option from within the [groupBy method](https://pbeshai.github.io/tidy/docs/api/groupby). Another example is Clojure's [group-by](https://clojuredocs.org/clojure.core/group-by), which offers a similar functionality.

**Proposed solution:** This proposal shows a draft implementation of `aq.objects({ preserveGroups })`. This option would not affect prior code, as the lack of presence of the options would result in the typical flattening behavior.

Examples of the output of these groupings is as follows:
```javascript
const df = aq.from(cars)
	.sample(10)
	.groupby(['Origin'])
    
df.objects({ preserveGroups: 'objects' });
// => {
//	USA: [ rows of USA cars ],
//	Europe: [ rows of European cars ],
//	Japan: [ rows of Japanese cars ]
//    }

df.objects({ preserveGroups: 'entries' });
// => [["USA", [ rows of USA cars ]],
//     ["Europe", [ rows of European cars ]],
//     ["Japan", [ rows of Japanese cars ]]]

df.objects({ preserveGroups: 'maps' });
// => {
//	USA => [ rows of USA cars ],
//	Europe => [ rows of European cars ],
//	Japan => [ rows of Japanese cars ]
//     }
```

When working with more complex groupings, outputs are nested.
```javascript
const df = aq.from(cars)
	.derive({ year: d => op.year(d.Year) })
	.sample(10)
	.groupby(['Origin', 'year']);
    
df.objects({ preserveGroups: 'maps' })
// => {
//	USA => {
//		1969 => [ rows of USA cars from 1969 ],
//		1970 => [ rows of USA cars from 1970 ],
//		1971 => [ rows of USA cars from 1971 ],
//	       },
//	Europe => ...,
//	Japan => ....
//     }
```

### CODE REVIEW

**Comment by jheer** [comment]
Thanks @lsh for the suggestion and the draft PR! A few reactions:

- Group keys may not be strings, but the current PR builds up an object and hence all keys are coerced to strings. Arquero's groupby supports non-primitive keys including Dates, Objects, and Arrays. While "object" output requires string keys, one must still be careful about how those strings are generated (notably for general Array- or Object-valued keys). Meanwhile, "map" or "entries" output could in theory use actual values, not strings. What is the "right" design to follow here?

- While perhaps more of an internal implementation detail, it would be satisfying to use Arquero transformations directly to generate the output, rather than specialized one-off methods. For example, one might construct a grouped object that is one-level deep like so:

  ```js
  {
    const dt = aq.table({
        key: ['a', 'a', 'b', 'b', 'c', 'c'],
        num: [1, 2, 3, 4, 5, 6]
      })
      .groupby('key');

    return dt.create({ data: { objects: dt.objects() } }) // table with one object column, groups preserved
      .rollup({ value: op.array_agg('objects') }) // group row objects into per-group arrays
      .rollup({ output: op.object_agg('key', 'value') }) // consolidate into a single object
      .get('output', 0); // extract the single aggregated object
  }
  ```

  The code above isn't quite right (it doesn't handle filtering correctly), and it only supports one-level of depth, but hopefully gives a sense of what I'm thinking. This gives us an opportunity to see how well Arquero can support custom nested data manipulation using the provided verbs and functions. (In fact, underlying the [`object_agg` method](https://github.com/uwdata/arquero/blob/master/src/op/aggregate-functions.js#L105) is a collector that actually builds out an entries array, so returning entries, or creating an Object or Map from them, is straightforward.)

- There are also a few modifications I might recommend to the current PR approach (the scan visitor is getting pretty bloated...), but those take a backseat to bigger design questions for now.

Thanks again!!

**Comment by ericemc3** [comment]
Interesting indeed, i precisely wanted to achieve something like that few days ago, for A D3 viz with a d3.line() generator by groups.

I had to derive a new datum variable to store the current row (at least part of it) as an object:
```
const dt = aq.table({
    country: ["France", "France", "France", "Germany", "Germany", "Germany", "Japan", "Japan", "Japan"],
    year: [2017, 2018, 2019, 2017, 2018, 2019, 2017, 2018, 2019], 
    expenditure: [52710, 51410, 52229, 45340, 46512, 51190, 46542, 46618, 46562]})
  
  return dt.groupby('country')
              .derive({datum: d => ({year: d.year, expenditure: d.expenditure})})
              .rollup({sub_table: d => op.array_agg(d.datum)})  
```
an Arquero table beeing iterable and directly readable in D3, it is very handy.

I didn't noticed the `create()` function, good to know it!

I first tried something like
`.derive({datum: d => d)`
but eventually understood why this couldn't work.

maybe a new op like this one could prove useful:
`.derive({datum: d => op.to_object(d))`

**Comment by jheer** [comment]
Here's a more sophisticated example with nested groups, implemented in terms of Arquero verbs:

```js
{
  function objectsGrouped(table) {
    const obj = table.objects();
    if (!table.isGrouped()) return obj;

    const { names } = table.groups();
    const val = 'val'; // TODO: ensure no conflict with existing column names

    // TODO: handle filtered tables without using reify
    let ot = table.reify().create({ data: { [val]: obj } })
      .rollup({ val: op.array_agg(val) });

    for (let i = names.length; --i >= 0;) {
      ot = ot.groupby(names.slice(0, i))
        .rollup({ [val]: op.object_agg(names[i], val) });
    }

    return ot.get(val, 0);
  }

  return objectsGrouped(
    aq.table({
      k1: ['a', 'a', 'b', 'b', 'c', 'c', 'a', 'a', 'b', 'b', 'c', 'c'],
      k2: ['x', 'y', 'x', 'y', 'x', 'y', 'x', 'y', 'x', 'y', 'x', 'y'],
      num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    })
    .groupby('k1', 'k2')
  );
}
```

**Comment by lsh** [comment]
Thanks for the feedback and examples! I think the point about non-primitive keys brings up an interesting question about use cases and design. Maybe only Map (or [InternMap](https://next.observablehq.com/@mbostock/internmap) given the ability to use Date objects as keys) is the right fit for preserving grouped output.

**Comment by MarioDelgadoSr** [comment]
Unless I'm missing something, the create method is missing from the API documentation: https://uwdata.github.io/arquero/api/

**Comment by jheer** [comment]
Hi @MarioDelgadoSr, you're right that `table.create` is not in the documentation. It is left out because it is intended for internal use, and is not part of the "official" API with respect to semantic versioning, etc. However, as we're discussing an internal implementation it is relevant here. That said, before this PR lands we might want to revise the approach to avoid using `create`. I'm thinking about possible alternatives, perhaps including an object generation `op` function as @ericemc3 suggests.

**Comment by lsh** [comment]
I'm not sure if this is an *ideal* solution, but adding an `op.from_entries` to the `op/object.js` makes it possible to do the following.
```javascript
function deriveObject(table) {
  const names = table.columnNames();
  let otb = table.params({ names: names }).derive({ val: (d) => [] });
  for (let i = 0; i < names.length; i++) {
    otb = otb.params({ i: i }).derive({
      val: (d, $) => op.concat(d.val, [[$.names[$.i], d[$.names[$.i]]]])
    });
  }
  otb = otb.derive({ val: (d) => op.from_entries(d.val) });
  return otb;
}
```
When substituting
```
let ot = deriveObject(table).rollup({ val: op.array_agg(val) });
```
for
```javascript
table.reify().create({ data: { [val]: obj } })
      .rollup({ val: op.array_agg(val) });
```
I seemed to get the same output and avoided the `create()` and `reify()`.

**Comment by jheer** [comment]
Thanks @lsh! A few more thoughts before we're ready for merge.

- We should target the `v4.1.0` branch. Note that this branch already has `map_agg` and `entries_agg` aggregate functions.
- For the map hierarchy creation, the following is both efficient and uses the least code:

  ```js
  dt.select() // select away all existing columns, so they are not copied
    .reify() // condense filtered tables, reindex groups if needed
    .create({ data: { [val]: obj } }) // as before...
    .array_agg(...) // etc.
  ```
- We should include test cases in `test/table/column-table-test.js`.
- I'm happy to add logic for ensuring no column name collisions once the above parts are in shape.
- I want to think more about the option name (e.g., `preserveGroups` vs. `groups` vs. ???), but can easily make any changes once the rest is in order.
- I can update documentation, too.

Thanks again!

**Comment by lsh** [comment]
Closing in favor of #126

**Pull request closed without merging**
